'use client';

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:3001';

export interface AptosWallet {
  address: string;
  publicKey: string;
  isAutoGenerated: boolean;
  network: string;
  balance?: string;
  createdAt: Date;
}

export interface User {
  address: string;
  role: string;
  displayName?: string;
  email?: string;
  ssoId?: string;
  ssoProvider?: string;
  aptosWallet?: AptosWallet;
}

interface AuthContextType {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  loadingWallet: boolean;
  login: (accessToken: string, refreshToken: string, address: string, role: string) => void;
  logout: () => void;
  refreshToken: () => Promise<boolean>;
  updateUser: (user: Partial<User>) => void;
  refreshWallet: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [loadingWallet, setLoadingWallet] = useState(false);
  const router = useRouter();

  // Load user from localStorage and verify token
  useEffect(() => {
    const initAuth = async () => {
      // Explicit client-side check to prevent any SSR issues
      if (typeof window === 'undefined') {
        setIsLoading(false);
        return;
      }

      const accessToken = localStorage.getItem('accessToken');
      const userAddress = localStorage.getItem('userAddress');
      const userRole = localStorage.getItem('userRole');

      if (accessToken && userAddress && userRole) {
        try {
          // Verify token with backend
          const response = await fetch(`${API_BASE_URL}/api/auth/me`, {
            headers: {
              Authorization: `Bearer ${accessToken}`,
            },
          });

          if (response.ok) {
            const data = await response.json();
            if (data.success && data.data.user) {
              setUser({
                address: data.data.user.address,
                role: data.data.user.role,
                displayName: data.data.user.displayName,
                email: data.data.user.email,
              });
              // Fetch wallet info after setting user
              await fetchWalletInfo();
            } else {
              // Token invalid, clear storage
              clearAuth();
            }
          } else {
            // Try to refresh token
            const refreshed = await tryRefreshToken();
            if (!refreshed) {
              clearAuth();
            }
          }
        } catch (error) {
          console.error('Auth initialization error:', error);
          clearAuth();
        }
      }

      setIsLoading(false);
    };

    initAuth();
  }, []);

  const fetchWalletInfo = async () => {
    if (typeof window === 'undefined') return;

    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) return;

    setLoadingWallet(true);
    try {
      const response = await fetch(`${API_BASE_URL}/api/auth/wallet-info`, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });

      if (response.ok) {
        const data = await response.json();
        if (data.success && data.data.wallet) {
          setUser(prev => prev ? {
            ...prev,
            aptosWallet: {
              address: data.data.wallet.address,
              publicKey: data.data.wallet.publicKey,
              isAutoGenerated: data.data.wallet.isAutoGenerated,
              network: data.data.wallet.network,
              balance: data.data.wallet.balance,
              createdAt: new Date(data.data.wallet.createdAt),
            }
          } : null);
        }
      }
    } catch (error) {
      console.error('Failed to fetch wallet info:', error);
    } finally {
      setLoadingWallet(false);
    }
  };

  const clearAuth = () => {
    if (typeof window !== 'undefined') {
      localStorage.removeItem('accessToken');
      localStorage.removeItem('refreshToken');
      localStorage.removeItem('userAddress');
      localStorage.removeItem('userRole');
    }
    setUser(null);
  };

  const login = useCallback((
    accessToken: string,
    refreshToken: string,
    address: string,
    role: string
  ) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('accessToken', accessToken);
      localStorage.setItem('refreshToken', refreshToken);
      localStorage.setItem('userAddress', address);
      localStorage.setItem('userRole', role);
    }

    setUser({
      address,
      role,
    });
  }, []);

  const logout = useCallback(async () => {
    if (typeof window === 'undefined') return;

    const accessToken = localStorage.getItem('accessToken');

    try {
      // Call backend logout endpoint
      if (accessToken) {
        await fetch(`${API_BASE_URL}/api/auth/logout`, {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        });
      }
    } catch (error) {
      console.error('Logout error:', error);
    }

    clearAuth();
    router.push('/auth');
  }, [router]);

  const tryRefreshToken = async (): Promise<boolean> => {
    if (typeof window === 'undefined') return false;

    const refreshToken = localStorage.getItem('refreshToken');
    if (!refreshToken) return false;

    try {
      const response = await fetch(`${API_BASE_URL}/api/auth/refresh`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ refreshToken }),
      });

      if (response.ok) {
        const data = await response.json();
        if (data.success && data.data.accessToken) {
          localStorage.setItem('accessToken', data.data.accessToken);
          return true;
        }
      }
    } catch (error) {
      console.error('Token refresh error:', error);
    }

    return false;
  };

  const refreshToken = useCallback(async (): Promise<boolean> => {
    return tryRefreshToken();
  }, []);

  const updateUser = useCallback((updates: Partial<User>) => {
    setUser(prev => prev ? { ...prev, ...updates } : null);
  }, []);

  const refreshWallet = useCallback(async () => {
    await fetchWalletInfo();
  }, []);

  const value: AuthContextType = {
    user,
    isAuthenticated: !!user,
    isLoading,
    loadingWallet,
    login,
    logout,
    refreshToken,
    updateUser,
    refreshWallet,
  };

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}
