import { NextRequest, NextResponse } from 'next/server';
import { rawQuery } from '@/lib/server/db/client';
import { logger } from '@/lib/server/utils/logger';
import { requireAuth } from '@/lib/server/middleware/auth';
import { WalletService } from '@/lib/server/services/walletService';

export async function GET(request: NextRequest) {
  try {
    const userAuth = await requireAuth(request);

    // Check if requireAuth returned an error response
    if (userAuth instanceof NextResponse) {
      return userAuth;
    }

    const address = userAuth.address;

    // Get user's wallet information
    const users = await rawQuery(
      `SELECT address, wallet_public_key, wallet_generated, wallet_created_at,
              sso_provider, sso_id, email
       FROM users
       WHERE address = $1`,
      [address]
    );

    if (users.length === 0) {
      return NextResponse.json(
        { success: false, error: 'User not found', message: 'User does not exist' },
        { status: 404 }
      );
    }

    const user = users[0];

    // Check if user has a wallet
    if (!user.wallet_public_key || !user.wallet_generated) {
      return NextResponse.json(
        {
          success: false,
          error: 'Wallet not found',
          message: 'User does not have a wallet',
          hasWallet: false,
        },
        { status: 404 }
      );
    }

    // Get wallet balance
    let balance = '0';
    let accountExists = false;
    try {
      accountExists = await WalletService.accountExists(user.address);
      if (accountExists) {
        const balanceValue = await WalletService.getBalance(user.address);
        balance = balanceValue.toString();
      }
    } catch (balanceError) {
      logger.warn('Failed to get wallet balance', {
        address: user.address,
        error: balanceError,
      });
    }

    const network = process.env.APTOS_NETWORK || 'testnet';

    return NextResponse.json({
      success: true,
      data: {
        wallet: {
          address: user.address,
          publicKey: user.wallet_public_key,
          isAutoGenerated: user.wallet_generated,
          network,
          balance,
          accountExists,
          createdAt: user.wallet_created_at,
        },
      },
    });
  } catch (error) {
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json(
        { success: false, error: 'Unauthorized', message: 'Not authenticated' },
        { status: 401 }
      );
    }
    logger.error('Failed to get wallet info', { error });
    return NextResponse.json(
      { success: false, error: 'Internal server error', message: 'Failed to get wallet info' },
      { status: 500 }
    );
  }
}