/**
 * Wallet Components Test Suite
 *
 * Tests for wallet-related components including:
 * - AddressDisplay
 * - WalletDashboardCard
 * - WalletWelcomeModal
 * - WalletNotificationBanner
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { AddressDisplay } from '../AddressDisplay';
import { WalletDashboardCard } from '../WalletDashboardCard';
import { WalletNotificationBanner } from '../WalletNotificationBanner';
import { AptosWallet } from '@/lib/auth/AuthContext';

// Mock wallet data
const mockWallet: AptosWallet = {
  address: '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
  publicKey: '0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890',
  isAutoGenerated: true,
  network: 'testnet',
  balance: '100000000', // 1 APT in octas
  createdAt: new Date('2024-01-01'),
};

// Mock clipboard API
const mockClipboard = {
  writeText: vi.fn(),
};
Object.assign(navigator, { clipboard: mockClipboard });

// Mock window.open
const mockWindowOpen = vi.fn();
window.open = mockWindowOpen;

describe('AddressDisplay', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should render short address format by default', () => {
    render(<AddressDisplay address={mockWallet.address} />);

    // Should show shortened address (0x1234...cdef)
    const addressElement = screen.getByText(/0x1234...cdef/i);
    expect(addressElement).toBeTruthy();
  });

  it('should render full address when format is "full"', () => {
    render(<AddressDisplay address={mockWallet.address} format="full" />);

    const addressElement = screen.getByText(mockWallet.address);
    expect(addressElement).toBeTruthy();
  });

  it('should copy address to clipboard when copy button is clicked', async () => {
    render(<AddressDisplay address={mockWallet.address} copyable={true} />);

    const copyButton = screen.getByLabelText(/copy address/i);
    fireEvent.click(copyButton);

    await waitFor(() => {
      expect(mockClipboard.writeText).toHaveBeenCalledWith(mockWallet.address);
    });
  });

  it('should open explorer link when explorer button is clicked', () => {
    render(
      <AddressDisplay
        address={mockWallet.address}
        linkToExplorer={true}
        network="testnet"
      />
    );

    const explorerButton = screen.getByLabelText(/view in explorer/i);
    fireEvent.click(explorerButton);

    expect(mockWindowOpen).toHaveBeenCalledWith(
      expect.stringContaining(mockWallet.address),
      '_blank',
      'noopener,noreferrer'
    );
  });

  it('should not render copy button when copyable is false', () => {
    render(<AddressDisplay address={mockWallet.address} copyable={false} />);

    const copyButton = screen.queryByLabelText(/copy address/i);
    expect(copyButton).toBeFalsy();
  });
});

describe('WalletDashboardCard', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should render wallet information correctly', () => {
    render(<WalletDashboardCard wallet={mockWallet} />);

    // Check for wallet title
    expect(screen.getByText(/your aptos wallet/i)).toBeTruthy();

    // Check for auto-generated badge
    expect(screen.getByText(/auto-generated/i)).toBeTruthy();

    // Check for address section
    expect(screen.getByText(/address/i)).toBeTruthy();

    // Check for balance section
    expect(screen.getByText(/balance/i)).toBeTruthy();
  });

  it('should display formatted balance', () => {
    render(<WalletDashboardCard wallet={mockWallet} />);

    // Balance should be formatted (1 APT from 100000000 octas)
    expect(screen.getByText(/1\.00/)).toBeTruthy();
    expect(screen.getByText(/APT/i)).toBeTruthy();
  });

  it('should show network badge', () => {
    render(<WalletDashboardCard wallet={mockWallet} />);

    expect(screen.getByText(/testnet/i)).toBeTruthy();
  });

  it('should open explorer when View in Explorer button is clicked', () => {
    render(<WalletDashboardCard wallet={mockWallet} />);

    const explorerButton = screen.getByText(/view in explorer/i);
    fireEvent.click(explorerButton);

    expect(mockWindowOpen).toHaveBeenCalled();
  });

  it('should call onViewDetails when Details button is clicked', () => {
    const mockOnViewDetails = vi.fn();
    render(
      <WalletDashboardCard
        wallet={mockWallet}
        onViewDetails={mockOnViewDetails}
      />
    );

    const detailsButton = screen.getByText(/details/i);
    fireEvent.click(detailsButton);

    expect(mockOnViewDetails).toHaveBeenCalled();
  });

  it('should display security information', () => {
    render(<WalletDashboardCard wallet={mockWallet} />);

    expect(screen.getByText(/secured with aes-256/i)).toBeTruthy();
  });

  it('should display creation date', () => {
    render(<WalletDashboardCard wallet={mockWallet} />);

    // Check for formatted date
    expect(screen.getByText(/created.*january.*2024/i)).toBeTruthy();
  });
});

describe('WalletNotificationBanner', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    localStorage.clear();
  });

  it('should render banner when not previously dismissed', () => {
    render(<WalletNotificationBanner />);

    expect(screen.getByText(/your aptos wallet is ready/i)).toBeTruthy();
  });

  it('should not render banner when previously dismissed', () => {
    localStorage.setItem('wallet-banner-dismissed', 'true');

    render(<WalletNotificationBanner />);

    expect(screen.queryByText(/your aptos wallet is ready/i)).toBeFalsy();
  });

  it('should dismiss banner when close button is clicked', async () => {
    render(<WalletNotificationBanner />);

    const closeButton = screen.getByLabelText(/dismiss/i);
    fireEvent.click(closeButton);

    await waitFor(() => {
      expect(localStorage.getItem('wallet-banner-dismissed')).toBe('true');
    });

    // Banner should disappear
    expect(screen.queryByText(/your aptos wallet is ready/i)).toBeFalsy();
  });

  it('should call onViewWallet when View Wallet button is clicked', () => {
    const mockOnViewWallet = vi.fn();
    render(<WalletNotificationBanner onViewWallet={mockOnViewWallet} />);

    const viewButton = screen.getByText(/view wallet/i);
    fireEvent.click(viewButton);

    expect(mockOnViewWallet).toHaveBeenCalled();
  });

  it('should call onLearnMore when Learn More button is clicked', () => {
    const mockOnLearnMore = vi.fn();
    render(<WalletNotificationBanner onLearnMore={mockOnLearnMore} />);

    const learnButton = screen.getByText(/learn more/i);
    fireEvent.click(learnButton);

    expect(mockOnLearnMore).toHaveBeenCalled();
  });
});

describe('Wallet API Utilities', () => {
  it('should format addresses correctly', async () => {
    const { formatAddress } = await import('@/lib/api/wallet');

    const fullAddress = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef';
    const formatted = formatAddress(fullAddress, 4);

    expect(formatted).toBe('0x1234...cdef');
  });

  it('should format balance correctly', async () => {
    const { formatBalance } = await import('@/lib/api/wallet');

    // 1 APT = 100000000 octas
    const balance = '100000000';
    const formatted = formatBalance(balance, 8);

    expect(formatted).toMatch(/1\.00/);
  });

  it('should generate correct explorer URLs', async () => {
    const { getExplorerUrl } = await import('@/lib/api/wallet');

    const url = getExplorerUrl(mockWallet.address, 'testnet');

    expect(url).toContain('explorer.aptoslabs.com');
    expect(url).toContain(mockWallet.address);
    expect(url).toContain('testnet');
  });
});

describe('Accessibility', () => {
  it('should have proper ARIA labels on interactive elements', () => {
    render(<AddressDisplay address={mockWallet.address} copyable linkToExplorer />);

    expect(screen.getByLabelText(/copy address/i)).toBeTruthy();
    expect(screen.getByLabelText(/view in explorer/i)).toBeTruthy();
  });

  it('should support keyboard navigation', () => {
    render(<AddressDisplay address={mockWallet.address} copyable />);

    const copyButton = screen.getByLabelText(/copy address/i);

    // Button should be focusable
    copyButton.focus();
    expect(document.activeElement).toBe(copyButton);
  });

  it('should have proper role attributes', () => {
    render(<WalletNotificationBanner />);

    // Alert component should have role="alert"
    const alert = screen.getByRole('alert');
    expect(alert).toBeTruthy();
  });
});

describe('Error Handling', () => {
  it('should handle clipboard API failure gracefully', async () => {
    mockClipboard.writeText.mockRejectedValueOnce(new Error('Clipboard error'));

    render(<AddressDisplay address={mockWallet.address} copyable />);

    const copyButton = screen.getByLabelText(/copy address/i);
    fireEvent.click(copyButton);

    await waitFor(() => {
      // Should not throw error, just fail silently
      expect(mockClipboard.writeText).toHaveBeenCalled();
    });
  });

  it('should handle missing balance gracefully', () => {
    const walletWithoutBalance = { ...mockWallet, balance: undefined };

    render(<WalletDashboardCard wallet={walletWithoutBalance} />);

    // Should show 0 balance
    expect(screen.getByText(/0\.00/)).toBeTruthy();
  });

  it('should handle invalid addresses gracefully', () => {
    render(<AddressDisplay address="" />);

    // Should render without crashing
    expect(screen.getByRole('code')).toBeTruthy();
  });
});

describe('Responsive Design', () => {
  it('should render mobile-friendly on small screens', () => {
    // Set viewport to mobile size
    global.innerWidth = 375;
    global.dispatchEvent(new Event('resize'));

    render(<WalletDashboardCard wallet={mockWallet} />);

    // Component should render without errors
    expect(screen.getByText(/your aptos wallet/i)).toBeTruthy();
  });
});
