'use client';

import React, { useState } from 'react';
import { Wallet, ChevronDown, ExternalLink, Info, History } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { formatAddress, formatBalance, getExplorerUrl } from '@/lib/api/wallet';
import { getCoinSymbol } from '@/lib/api/aptos';
import { AptosWallet } from '@/lib/auth/AuthContext';
import { cn } from '@/lib/utils';

interface WalletHeaderDisplayProps {
  wallet: AptosWallet;
  loading?: boolean;
  onViewWallet?: () => void;
  onViewTransactions?: () => void;
  className?: string;
}

export function WalletHeaderDisplay({
  wallet,
  loading = false,
  onViewWallet,
  onViewTransactions,
  className,
}: WalletHeaderDisplayProps) {
  const explorerUrl = getExplorerUrl(wallet.address, wallet.network);

  if (loading) {
    return (
      <div className={cn('flex items-center gap-2', className)}>
        <Skeleton className="h-9 w-32" />
      </div>
    );
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          className={cn(
            'flex items-center gap-2 h-9 px-3',
            className
          )}
        >
          <div className="flex h-6 w-6 items-center justify-center rounded-md bg-gradient-to-br from-violet-600 to-purple-600">
            <Wallet className="h-3.5 w-3.5 text-white" />
          </div>
          <div className="flex flex-col items-start gap-0.5">
            <span className="text-xs font-mono leading-none">
              {formatAddress(wallet.address, 3)}
            </span>
          </div>
          <ChevronDown className="h-4 w-4 opacity-50" />
        </Button>
      </DropdownMenuTrigger>

      <DropdownMenuContent align="end" className="w-72">
        {/* Wallet Info Header */}
        <div className="px-2 py-3 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Your Aptos Wallet</span>
            {wallet.isAutoGenerated && (
              <Badge variant="secondary" className="text-xs">
                Auto-Generated
              </Badge>
            )}
          </div>

          {/* Balance Display */}
          <div className="rounded-lg bg-muted p-3 space-y-1">
            <p className="text-xs text-muted-foreground">Balance</p>
            <div className="flex items-baseline gap-2">
              <span className="text-lg font-bold">
                {formatBalance(wallet.balance || '0')}
              </span>
              <span className="text-xs text-muted-foreground">{getCoinSymbol()}</span>
            </div>
          </div>

          {/* Address Display */}
          <div className="space-y-1">
            <p className="text-xs text-muted-foreground">Address</p>
            <code className="block text-xs font-mono bg-muted px-2 py-1 rounded break-all">
              {formatAddress(wallet.address, 6)}
            </code>
          </div>

          {/* Network Badge */}
          <div className="flex items-center gap-2">
            <p className="text-xs text-muted-foreground">Network:</p>
            <Badge variant="outline" className="text-xs capitalize">
              {wallet.network}
            </Badge>
          </div>
        </div>

        <DropdownMenuSeparator />

        {/* Actions */}
        {onViewWallet && (
          <DropdownMenuItem onClick={onViewWallet}>
            <Info className="h-4 w-4" />
            <span>View Wallet Details</span>
          </DropdownMenuItem>
        )}

        {onViewTransactions && (
          <DropdownMenuItem onClick={onViewTransactions}>
            <History className="h-4 w-4" />
            <span>Transaction History</span>
          </DropdownMenuItem>
        )}

        <DropdownMenuItem
          onClick={() => window.open(explorerUrl, '_blank', 'noopener,noreferrer')}
        >
          <ExternalLink className="h-4 w-4" />
          <span>View in Explorer</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// Compact version for mobile or small spaces
export function WalletHeaderDisplayCompact({
  wallet,
  loading = false,
  onViewWallet,
  className,
}: {
  wallet: AptosWallet;
  loading?: boolean;
  onViewWallet?: () => void;
  className?: string;
}) {
  if (loading) {
    return <Skeleton className="h-9 w-9 rounded-full" />;
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="icon"
          className={cn('h-9 w-9 rounded-full', className)}
        >
          <div className="flex h-6 w-6 items-center justify-center rounded-full bg-gradient-to-br from-violet-600 to-purple-600">
            <Wallet className="h-3.5 w-3.5 text-white" />
          </div>
        </Button>
      </DropdownMenuTrigger>

      <DropdownMenuContent align="end" className="w-64">
        <div className="px-2 py-3 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Wallet</span>
            <Badge variant="secondary" className="text-xs">
              {wallet.network}
            </Badge>
          </div>

          <div className="space-y-1">
            <p className="text-xs text-muted-foreground">Balance</p>
            <div className="flex items-baseline gap-1">
              <span className="text-base font-bold">
                {formatBalance(wallet.balance || '0')}
              </span>
              <span className="text-xs text-muted-foreground">{getCoinSymbol()}</span>
            </div>
          </div>
        </div>

        <DropdownMenuSeparator />

        {onViewWallet && (
          <DropdownMenuItem onClick={onViewWallet}>
            <Wallet className="h-4 w-4" />
            <span>View Details</span>
          </DropdownMenuItem>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// Skeleton loader for header wallet display
export function WalletHeaderDisplaySkeleton({ className }: { className?: string }) {
  return (
    <div className={cn('flex items-center gap-2', className)}>
      <Skeleton className="h-9 w-32" />
    </div>
  );
}
