'use client';

import React, { useEffect, useState } from 'react';
import { Sparkles, Shield, CheckCircle, BookOpen } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { AddressDisplay } from './AddressDisplay';
import { AptosWallet } from '@/lib/auth/AuthContext';

interface WalletWelcomeModalProps {
  wallet: AptosWallet;
  open?: boolean;
  onClose?: () => void;
  onLearnMore?: () => void;
}

const STORAGE_KEY = 'wallet-welcome-shown';

export function WalletWelcomeModal({
  wallet,
  open: controlledOpen,
  onClose,
  onLearnMore,
}: WalletWelcomeModalProps) {
  const [open, setOpen] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);

  useEffect(() => {
    // Check if this is the first time showing the modal
    const hasShown = localStorage.getItem(STORAGE_KEY);

    if (!hasShown && wallet.isAutoGenerated && controlledOpen !== false) {
      setOpen(true);
      setShowConfetti(true);

      // Confetti animation duration
      const timer = setTimeout(() => setShowConfetti(false), 3000);
      return () => clearTimeout(timer);
    }
  }, [wallet, controlledOpen]);

  const handleClose = () => {
    localStorage.setItem(STORAGE_KEY, 'true');
    setOpen(false);
    onClose?.();
  };

  const handleLearnMore = () => {
    handleClose();
    onLearnMore?.();
  };

  const isControlled = controlledOpen !== undefined;
  const isOpen = isControlled ? controlledOpen : open;

  return (
    <>
      {showConfetti && <ConfettiAnimation />}

      <Dialog open={isOpen} onOpenChange={isControlled ? onClose : setOpen}>
        <DialogContent className="sm:max-w-xl">
          <DialogHeader className="space-y-4">
            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-gradient-to-br from-violet-600 to-purple-600 animate-in zoom-in-50 duration-300">
              <Sparkles className="h-8 w-8 text-white" />
            </div>

            <DialogTitle className="text-center text-2xl font-bold">
              Welcome to Web3!
            </DialogTitle>

            <DialogDescription className="text-center text-base">
              Your Aptos blockchain wallet is ready to use
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6 py-4">
            {/* Wallet Address Section */}
            <div className="rounded-lg border bg-muted/50 p-4 space-y-3">
              <div className="flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-green-600" />
                <h3 className="font-semibold">Your Wallet Address</h3>
              </div>

              <AddressDisplay
                address={wallet.address}
                format="full"
                copyable
                showQR
                network={wallet.network}
                className="flex-wrap"
              />

              <p className="text-xs text-muted-foreground">
                This is your unique blockchain address. You can share it to receive funds.
              </p>
            </div>

            {/* Features List */}
            <div className="space-y-3">
              <Feature
                icon={<Shield className="h-5 w-5" />}
                title="Secure & Encrypted"
                description="Your private keys are encrypted with AES-256 and stored securely"
              />

              <Feature
                icon={<CheckCircle className="h-5 w-5" />}
                title="Auto-Generated for You"
                description="We created this wallet automatically when you signed up"
              />

              <Feature
                icon={<BookOpen className="h-5 w-5" />}
                title="Ready for Governance"
                description="Use your wallet to vote on proposals and request reimbursements"
              />
            </div>

            {/* Security Notice */}
            <div className="rounded-lg border border-yellow-200 bg-yellow-50 dark:bg-yellow-950/20 dark:border-yellow-900 p-4">
              <div className="flex gap-3">
                <Shield className="h-5 w-5 text-yellow-600 dark:text-yellow-500 flex-shrink-0 mt-0.5" />
                <div className="space-y-1 text-sm">
                  <p className="font-semibold text-yellow-900 dark:text-yellow-100">
                    Important Security Information
                  </p>
                  <p className="text-yellow-800 dark:text-yellow-200">
                    Your wallet is custodial, meaning your private keys are securely managed by us.
                    Always verify transactions before approving them.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col-reverse sm:flex-row gap-2 pt-4">
            <Button
              variant="outline"
              onClick={handleLearnMore}
              className="flex-1"
            >
              Learn More
            </Button>
            <Button
              onClick={handleClose}
              className="flex-1 bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700"
            >
              Got It!
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

// Feature component for the features list
function Feature({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="flex gap-3">
      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary flex-shrink-0">
        {icon}
      </div>
      <div className="space-y-1">
        <h4 className="font-medium text-sm">{title}</h4>
        <p className="text-sm text-muted-foreground">{description}</p>
      </div>
    </div>
  );
}

// Simple confetti animation component
function ConfettiAnimation() {
  return (
    <div className="fixed inset-0 pointer-events-none z-50 overflow-hidden">
      {Array.from({ length: 50 }).map((_, i) => (
        <div
          key={i}
          className="absolute animate-confetti"
          style={{
            left: `${Math.random() * 100}%`,
            top: '-10px',
            animationDelay: `${Math.random() * 2}s`,
            animationDuration: `${2 + Math.random() * 2}s`,
          }}
        >
          <div
            className="w-2 h-2 rounded-full"
            style={{
              backgroundColor: [
                '#8b5cf6', // violet
                '#a855f7', // purple
                '#ec4899', // pink
                '#f59e0b', // amber
                '#3b82f6', // blue
              ][Math.floor(Math.random() * 5)],
            }}
          />
        </div>
      ))}
    </div>
  );
}

// Add this to your global CSS for the confetti animation
// @keyframes confetti {
//   0% { transform: translateY(0) rotateZ(0deg); opacity: 1; }
//   100% { transform: translateY(100vh) rotateZ(360deg); opacity: 0; }
// }
// .animate-confetti { animation: confetti linear forwards; }
