'use client';

import React, { useEffect, useState } from 'react';
import { Wallet, Shield, ExternalLink, Info } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Label } from '@/components/ui/label';
import { AddressDisplay } from './AddressDisplay';
import { formatBalance, getExplorerUrl, getWalletBalance } from '@/lib/api/wallet';
import { AptosWallet } from '@/lib/auth/AuthContext';
import { cn } from '@/lib/utils';

interface WalletDashboardCardProps {
  wallet: AptosWallet;
  onViewDetails?: () => void;
  className?: string;
}

export function WalletDashboardCard({
  wallet,
  onViewDetails,
  className,
}: WalletDashboardCardProps) {
  const [balance, setBalance] = useState<string | null>(wallet.balance || null);
  const [loadingBalance, setLoadingBalance] = useState(!wallet.balance);

  useEffect(() => {
    if (!wallet.balance) {
      fetchBalance();
    }
  }, [wallet.address]);

  const fetchBalance = async () => {
    setLoadingBalance(true);
    try {
      const bal = await getWalletBalance(wallet.address);
      setBalance(bal);
    } catch (error) {
      console.error('Failed to fetch balance:', error);
    } finally {
      setLoadingBalance(false);
    }
  };

  const handleViewExplorer = () => {
    const url = getExplorerUrl(wallet.address, wallet.network);
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  return (
    <Card className={cn('w-full', className)}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-violet-600 to-purple-600">
              <Wallet className="h-5 w-5 text-white" />
            </div>
            <div>
              <CardTitle className="text-lg">Your Aptos Wallet</CardTitle>
              {wallet.isAutoGenerated && (
                <Badge variant="secondary" className="mt-1">
                  Auto-Generated
                </Badge>
              )}
            </div>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Address Section */}
        <div className="space-y-2">
          <Label className="text-sm text-muted-foreground">Address</Label>
          <AddressDisplay
            address={wallet.address}
            format="short"
            copyable
            linkToExplorer
            network={wallet.network}
          />
        </div>

        {/* Balance Section */}
        <div className="space-y-2">
          <Label className="text-sm text-muted-foreground">Balance</Label>
          {loadingBalance ? (
            <Skeleton className="h-10 w-32" />
          ) : (
            <div className="flex items-baseline gap-2">
              <span className="text-2xl font-bold">
                {formatBalance(balance || '0')}
              </span>
              <span className="text-sm text-muted-foreground">APT</span>
            </div>
          )}
        </div>

        {/* Network Badge */}
        <div className="flex items-center gap-2">
          <Label className="text-sm text-muted-foreground">Network:</Label>
          <Badge variant="outline" className="capitalize">
            {wallet.network}
          </Badge>
        </div>
      </CardContent>

      <CardFooter className="flex flex-col gap-3">
        {/* Action Buttons */}
        <div className="flex w-full gap-2">
          <Button
            variant="outline"
            className="flex-1"
            onClick={handleViewExplorer}
          >
            <ExternalLink className="h-4 w-4" />
            View in Explorer
          </Button>
          {onViewDetails && (
            <Button
              variant="outline"
              className="flex-1"
              onClick={onViewDetails}
            >
              <Info className="h-4 w-4" />
              Details
            </Button>
          )}
        </div>

        {/* Security Info */}
        <div className="flex items-start gap-2 rounded-md bg-muted p-3 text-sm">
          <Shield className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-muted-foreground">
            Secured with AES-256 encryption. Your private keys are encrypted and stored securely.
          </p>
        </div>

        {/* Created Date */}
        <p className="text-xs text-muted-foreground text-center">
          Created {new Date(wallet.createdAt).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}
        </p>
      </CardFooter>
    </Card>
  );
}

// Loading skeleton for the wallet card
export function WalletDashboardCardSkeleton({ className }: { className?: string }) {
  return (
    <Card className={cn('w-full', className)}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <Skeleton className="h-10 w-10 rounded-lg" />
            <div className="space-y-2">
              <Skeleton className="h-5 w-32" />
              <Skeleton className="h-4 w-24" />
            </div>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Skeleton className="h-4 w-16" />
          <Skeleton className="h-8 w-48" />
        </div>

        <div className="space-y-2">
          <Skeleton className="h-4 w-16" />
          <Skeleton className="h-10 w-32" />
        </div>

        <div className="space-y-2">
          <Skeleton className="h-4 w-full" />
        </div>
      </CardContent>

      <CardFooter className="flex flex-col gap-3">
        <div className="flex w-full gap-2">
          <Skeleton className="h-10 flex-1" />
          <Skeleton className="h-10 flex-1" />
        </div>
        <Skeleton className="h-16 w-full" />
        <Skeleton className="h-4 w-32 mx-auto" />
      </CardFooter>
    </Card>
  );
}
