-- Migration: Add SSO Support
-- Description: Adds columns to support Single Sign-On authentication and auto-generated wallets

-- Add SSO-related columns to users table
DO $$
BEGIN
    -- Add sso_provider column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'sso_provider'
    ) THEN
        ALTER TABLE users ADD COLUMN sso_provider VARCHAR(50);
    END IF;

    -- Add sso_id column (unique identifier from SSO provider, e.g., NetID)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'sso_id'
    ) THEN
        ALTER TABLE users ADD COLUMN sso_id VARCHAR(255) UNIQUE;
    END IF;

    -- Add wallet_public_key column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'wallet_public_key'
    ) THEN
        ALTER TABLE users ADD COLUMN wallet_public_key VARCHAR(66);
    END IF;

    -- Add encrypted_private_key column (for auto-generated wallets)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'encrypted_private_key'
    ) THEN
        ALTER TABLE users ADD COLUMN encrypted_private_key TEXT;
    END IF;

    -- Add wallet_generated flag
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'wallet_generated'
    ) THEN
        ALTER TABLE users ADD COLUMN wallet_generated BOOLEAN DEFAULT FALSE;
    END IF;

    -- Add wallet_created_at timestamp
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'wallet_created_at'
    ) THEN
        ALTER TABLE users ADD COLUMN wallet_created_at TIMESTAMP;
    END IF;

    -- Add first_name column (from SSO profile)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'first_name'
    ) THEN
        ALTER TABLE users ADD COLUMN first_name VARCHAR(255);
    END IF;

    -- Add last_name column (from SSO profile)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'last_name'
    ) THEN
        ALTER TABLE users ADD COLUMN last_name VARCHAR(255);
    END IF;
END $$;

-- Create indexes for efficient SSO lookups
CREATE INDEX IF NOT EXISTS idx_users_sso_id ON users(sso_id);
CREATE INDEX IF NOT EXISTS idx_users_sso_provider ON users(sso_provider);
CREATE INDEX IF NOT EXISTS idx_users_wallet_generated ON users(wallet_generated);

-- Add constraint to ensure address is unique
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'users_address_unique'
    ) THEN
        ALTER TABLE users ADD CONSTRAINT users_address_unique UNIQUE (address);
    END IF;
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- Comments for documentation
COMMENT ON COLUMN users.sso_provider IS 'SSO provider identifier (e.g., nyu_sso, google_oauth)';
COMMENT ON COLUMN users.sso_id IS 'Unique identifier from SSO provider (e.g., NetID for NYU)';
COMMENT ON COLUMN users.wallet_public_key IS 'Aptos wallet public key (hex encoded)';
COMMENT ON COLUMN users.encrypted_private_key IS 'AES-256 encrypted private key for auto-generated wallets';
COMMENT ON COLUMN users.wallet_generated IS 'Flag indicating if wallet was auto-generated by the system';
COMMENT ON COLUMN users.wallet_created_at IS 'Timestamp when the wallet was created';