import { apiClient } from './client';
import { ApiResponse } from '../types/api';

export interface WalletInfo {
  address: string;
  publicKey: string;
  isAutoGenerated: boolean;
  network: string;
  balance?: string;
  createdAt: string;
}

export interface WalletTransaction {
  hash: string;
  type: 'sent' | 'received';
  amount: string;
  status: 'pending' | 'confirmed' | 'failed';
  timestamp: string;
  from: string;
  to: string;
}

export interface WalletExportData {
  address: string;
  publicKey: string;
  network: string;
  createdAt: string;
  warning: string;
}

/**
 * Create a wallet for the authenticated user
 */
export async function createWallet(): Promise<{ wallet: WalletInfo; existing: boolean; message: string } | null> {
  try {
    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) {
      throw new Error('Not authenticated');
    }

    const response = await apiClient.post<{ wallet: WalletInfo; existing: boolean; message: string }>(
      '/api/auth/create-wallet',
      {},
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      }
    );

    if (response.success && response.data) {
      return response.data;
    }

    throw new Error('Failed to create wallet');
  } catch (error) {
    console.error('Failed to create wallet:', error);
    throw error;
  }
}

/**
 * Get wallet information for the authenticated user
 */
export async function getWalletInfo(): Promise<WalletInfo | null> {
  try {
    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) {
      return null;
    }

    const response = await apiClient.get<{ wallet: WalletInfo }>(
      '/api/auth/wallet-info',
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      }
    );

    if (response.success && response.data) {
      return response.data.wallet;
    }

    return null;
  } catch (error) {
    console.error('Failed to get wallet info:', error);
    return null;
  }
}

/**
 * Get wallet balance for a specific address
 */
export async function getWalletBalance(address: string): Promise<string> {
  try {
    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) {
      return '0';
    }

    const response = await apiClient.get<{ balance: string }>(
      '/api/wallet/balance',
      {
        params: { address },
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      }
    );

    if (response.success && response.data) {
      return response.data.balance;
    }

    return '0';
  } catch (error) {
    console.error('Failed to get wallet balance:', error);
    return '0';
  }
}

/**
 * Get transaction history for the wallet
 */
export async function getWalletTransactions(
  address: string,
  limit: number = 50
): Promise<WalletTransaction[]> {
  try {
    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) {
      return [];
    }

    const response = await apiClient.get<{ transactions: WalletTransaction[] }>(
      '/api/wallet/transactions',
      {
        params: { address, limit },
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      }
    );

    if (response.success && response.data) {
      return response.data.transactions;
    }

    return [];
  } catch (error) {
    console.error('Failed to get wallet transactions:', error);
    return [];
  }
}

/**
 * Export wallet information (public data only, no private keys)
 */
export async function exportWalletInfo(): Promise<WalletExportData | null> {
  try {
    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) {
      return null;
    }

    const response = await apiClient.get<{ export: WalletExportData }>(
      '/api/wallet/export',
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      }
    );

    if (response.success && response.data) {
      return response.data.export;
    }

    return null;
  } catch (error) {
    console.error('Failed to export wallet info:', error);
    return null;
  }
}

/**
 * Get Aptos blockchain explorer URL for an address
 */
export function getExplorerUrl(address: string, network: string = 'testnet'): string {
  const baseUrl = network === 'mainnet'
    ? 'https://explorer.aptoslabs.com'
    : 'https://explorer.aptoslabs.com';

  return `${baseUrl}/account/${address}?network=${network}`;
}

/**
 * Get explorer URL for a transaction
 */
export function getTransactionExplorerUrl(hash: string, network: string = 'testnet'): string {
  const baseUrl = network === 'mainnet'
    ? 'https://explorer.aptoslabs.com'
    : 'https://explorer.aptoslabs.com';

  return `${baseUrl}/txn/${hash}?network=${network}`;
}

/**
 * Format wallet address for display (short format)
 */
export function formatAddress(address: string, chars: number = 4): string {
  if (!address || address.length < chars * 2) {
    return address;
  }
  return `${address.substring(0, chars + 2)}...${address.substring(address.length - chars)}`;
}

/**
 * Format balance for display
 * Supports both APT (8 decimals) and stablecoins (6 decimals)
 */
export function formatBalance(balance: string | number, decimals: number = 8): string {
  const num = typeof balance === 'string' ? parseFloat(balance) : balance;

  if (isNaN(num)) {
    return '0';
  }

  // Convert from smallest unit (e.g., octas for APT, micro-units for USDC)
  const amount = num / Math.pow(10, decimals);

  // Format with appropriate decimal places
  if (amount < 0.0001) {
    return amount.toExponential(2);
  }

  // Adjust max decimals based on coin type: USDC = 2, APT = 6
  const maxDecimals = decimals === 6 ? 2 : 6;

  return amount.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: maxDecimals,
  });
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}
