import { NextRequest, NextResponse } from 'next/server';
import { rawQuery } from '@/lib/server/db/client';
import { logger } from '@/lib/server/utils/logger';
import { requireAuth } from '@/lib/server/middleware/auth';
import { WalletService } from '@/lib/server/services/walletService';

export async function POST(request: NextRequest) {
  try {
    const userAuth = await requireAuth(request);

    // Check if requireAuth returned an error response
    if (userAuth instanceof NextResponse) {
      return userAuth;
    }

    const address = userAuth.address;

    // Check if user already has a wallet
    const users = await rawQuery(
      'SELECT address, wallet_public_key, wallet_generated, wallet_created_at FROM users WHERE address = $1',
      [address]
    );

    if (users.length === 0) {
      return NextResponse.json(
        { success: false, error: 'User not found', message: 'User does not exist' },
        { status: 404 }
      );
    }

    const user = users[0];

    // If user already has a wallet, return it
    if (user.wallet_public_key && user.wallet_generated) {
      logger.info('User already has wallet', { address });

      return NextResponse.json({
        success: true,
        data: {
          wallet: {
            address: user.address,
            publicKey: user.wallet_public_key,
            isAutoGenerated: true,
            createdAt: user.wallet_created_at,
          },
          message: 'Wallet already exists',
          existing: true,
        },
      });
    }

    // Generate new wallet
    logger.info('Creating wallet for user', { address });

    try {
      const wallet = await WalletService.generateWallet();

      // Update user with wallet information
      await rawQuery(
        `UPDATE users
         SET wallet_public_key = $1,
             encrypted_private_key = $2,
             wallet_generated = true,
             wallet_created_at = NOW(),
             updated_at = NOW()
         WHERE address = $3`,
        [wallet.publicKey, wallet.encryptedPrivateKey, address]
      );

      logger.info('Wallet created successfully', {
        address,
        walletAddress: wallet.address,
      });

      // Optionally fund the wallet on testnet
      if (process.env.APTOS_NETWORK === 'testnet' && process.env.AUTO_FUND_WALLETS === 'true') {
        try {
          const fundTxHash = await WalletService.fundWallet(wallet.address);
          if (fundTxHash) {
            logger.info('Wallet funded', {
              address: wallet.address,
              txHash: fundTxHash,
            });
          }
        } catch (fundError) {
          // Log but don't fail the request if funding fails
          logger.warn('Failed to fund wallet', {
            address: wallet.address,
            error: fundError,
          });
        }
      }

      return NextResponse.json(
        {
          success: true,
          data: {
            wallet: {
              address: wallet.address,
              publicKey: wallet.publicKey,
              isAutoGenerated: true,
              createdAt: new Date(),
            },
            message: 'Wallet created successfully',
            existing: false,
          },
        },
        { status: 201 }
      );
    } catch (walletError) {
      logger.error('Wallet creation failed', {
        address,
        error: walletError,
      });

      return NextResponse.json(
        {
          success: false,
          error: 'Wallet creation failed',
          message: walletError instanceof Error ? walletError.message : 'Failed to create wallet',
        },
        { status: 500 }
      );
    }
  } catch (error) {
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json(
        { success: false, error: 'Unauthorized', message: 'Not authenticated' },
        { status: 401 }
      );
    }
    logger.error('Create wallet error', { error });
    return NextResponse.json(
      { success: false, error: 'Internal server error', message: 'Failed to create wallet' },
      { status: 500 }
    );
  }
}